# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eda5f85ba2e6c963a655c5b9d92d4ad9ee61fbbc68ea734dfd505fa1ce9e0c91469c87e0af7d018236591ae1494a97de87672232dc842e37e5ea801e849e2cad

test:
  secret_key_base: abf7c8f8c8f00b2787acbbe0fdc6679839bd101b3f0b4647bedd32f124cf319f6eaae7de93f9b87b5702a1e28acd2f192776a24502552d0b178beadf621f0259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
